name = "XXX"
author = "蓝鲸，番茄鱼，电波囚人，阿虔"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fe939aa03165b2992985969d75281b5339e4f4332ded9a3ac3e6183e151dac8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
