name = "XXX"
author = "蓝鲸，番茄鱼，电波囚人，阿虔"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf0896ed0e1e1b1b5a8beb4b9da44565da8a768c71229e111e8c4d71341310ac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
